language: android
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - extra
script:
   - ./TestMeApp/gradlew build
before_install:
   - chmod +x ./TestMeApp/gradlew
